// @fctry: #bootstrap-primitive-composition
//
// Spec 0.28: bootstrap recipe runner — shell + types.
//
// The runner walks a recipe snapshot, runs pre-flight, executes each step
// through one of three shape-specific executors (filesystem-op,
// shell-command, mcp-tool), and assembles the per-step trace the bootstrap
// engine returns.
//
// This file declares the runner's public contract: the StepResult shape,
// the StepStatus enum, the ExecutorContext + Executor interface, and the
// RunnerEnvelope returned to callers. Chunk 3 lands the three concrete
// executor implementations; Chunk 4 wires the runner into the Bootstrap
// class itself.

import type { McpToolCaller } from './mcp-caller.js';
import type { ProjectContext } from './templates.js';
import type { Primitive, RecipeSnapshot, RecipeStep } from './types.js';

export type StepStatus = 'pending' | 'succeeded' | 'failed' | 'skipped' | 'not-run';

/**
 * Per-step result. Generated by the runner for every step in the recipe
 * (plus the structural register-in-registry trailer on success).
 *
 * `error_output` is a verbatim capture of stderr / failure-reason text
 * from the step — surfaced in the stop-and-report UI per S144.
 */
export interface StepResult {
  /** 0-based position in the recipe snapshot (or -1 for the trailer). */
  position: number;
  primitive_id: number | null; // null for the structural trailer
  primitive_name: string;
  shape: 'filesystem-op' | 'shell-command' | 'mcp-tool' | 'register-in-registry';
  status: StepStatus;
  /** Resolved parameters for this step (template tokens already substituted). */
  resolved_params: Record<string, string>;
  /** Verbatim stdout/stderr or operation summary, when produced. */
  output?: string;
  /** Verbatim error message, when status='failed'. */
  error_output?: string;
  /** Wall-clock timing — undefined for steps that didn't run. */
  started_at?: string;
  completed_at?: string;
}

/** Pre-flight check result for one step. */
export interface PreflightResult {
  position: number;
  primitive_name: string;
  shape: StepResult['shape'];
  ok: boolean;
  /** Human-readable reason when ok=false (binary not on PATH, etc.). */
  reason?: string;
  /** Resolved params, even when pre-flight failed (for trace rendering). */
  resolved_params: Record<string, string>;
}

/** Pre-flight envelope — one entry per step (including the trailer). */
export interface PreflightEnvelope {
  ok: boolean;
  steps: PreflightResult[];
}

/**
 * Context passed to every executor. Carries the project context (for token
 * resolution that happened in pre-flight), an MCP caller for mcp-tool steps,
 * and the resolved parameters for this step.
 */
export interface ExecutorContext {
  project: ProjectContext;
  resolved_params: Record<string, string>;
  /** When undefined, mcp-tool executors must surface "not configured" failures. */
  mcp_caller?: McpToolCaller;
  /** For Abandon cleanup — recorded by filesystem ops that mutate state. */
  cleanup_log?: CleanupLog;
}

/** A single executor for one primitive shape. */
export interface ShapeExecutor {
  /** Pre-flight: structural reachability without side effects. */
  preflight(primitive: Primitive, ctx: ExecutorContext): Promise<PreflightResult>;
  /** Execute. Returns the StepResult; never throws — failures land in status. */
  execute(primitive: Primitive, step: RecipeStep, ctx: ExecutorContext): Promise<StepResult>;
}

/**
 * Cleanup log used by Abandon (S147) to undo filesystem and git work the
 * runner itself performed. External side effects (mcp-tool, shell-command)
 * are reported as "left in place" rather than rolled back.
 *
 * Spec 0.29: external_side_effects entries carry a structured shape so
 * MCP-tool consumers can iterate over them programmatically (S162) and
 * mail-create-mailbox can surface a parseable mailbox-still-exists entry.
 *   - step:      1-based step position in the recipe (matches surface UI).
 *   - primitive: human-readable name of the primitive that produced it.
 *   - summary:   one-line, user-facing description of the side effect.
 */
export interface ExternalSideEffect {
  step: number;
  primitive: string;
  summary: string;
}

export interface CleanupLog {
  created_folders: string[];
  inited_git_repos: string[];
  /** Parent .gitignore appends — { path, original_content } per mutation. */
  gitignore_appends: { path: string; original_content: string }[];
  /** Spec 0.29: structured per-step external-side-effect entries (S162). */
  external_side_effects: ExternalSideEffect[];
}

export function newCleanupLog(): CleanupLog {
  return {
    created_folders: [],
    inited_git_repos: [],
    gitignore_appends: [],
    external_side_effects: [],
  };
}

/** Final envelope returned to the caller after the runner walks the recipe. */
export interface RunnerEnvelope {
  /** Overall status — succeeded when every step + trailer ran clean. */
  status: 'succeeded' | 'failed' | 'pre-flight-failed';
  /** The recipe snapshot the runner walked. */
  snapshot: RecipeSnapshot;
  /** Pre-flight results — present even on success (for the trace). */
  preflight: PreflightEnvelope;
  /** One result per step (in recipe order) plus the trailer at index N. */
  steps: StepResult[];
  /**
   * Index of the failed step, when status='failed'. Undefined on
   * pre-flight-failed (use preflight.steps for the per-step ✓/✗) and on
   * succeeded.
   */
  failed_at?: number;
  /** Cleanup log — populated for Abandon, present on every run. */
  cleanup: CleanupLog;
}

/**
 * Recipe trailer — the structural register-in-registry step. Synthesized
 * by the runner; not stored in project_type_recipe_steps.
 */
export const TRAILER_NAME = 'Register in setlist';
export const TRAILER_LABEL = '[final, automatic] Register in setlist';
